language: node_js
services:
  - mysql

before_install:
  - sudo mysql --version
  - mysql -e 'CREATE DATABASE IF NOT EXISTS ticket;'
  # - sudo mysql -e 'CREATE USER \'ticket\'@\'localhost\' IDENTIFIED WITH mysql_native_password AS \'ticket\';'
  # - sudo mysql -e 'CREATE USER ticket@localhost IDENTIFIED WITH mysql_native_password AS ticket;'
  # - sudo mysql -e 'GRANT USAGE ON *.* TO \'ticket\'@\'localhost\' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;'
  # - sudo mysql -e 'CREATE DATABASE IF NOT EXISTS `ticket`;'
  # - sudo mysql -e 'GRANT ALL PRIVILEGES ON `ticket`.* TO \'ticket\'@\'localhost\';'

before_script:
  - npm install -g gulp-cli
script:
  - gulp
  - npm test
  # - mysql -e ' SHOW DATABASES LIKE ticket;'
